### ISSUE TITLE
魅族mx5运行报错

### ISSUE THREAD

**Issue by a1b22003001** [Simon-Leeeeeeeee/XCodeScanner#4]
错误输出是
java.lang.RuntimeException: TextureReader Error! EGL MakeCurrent failure: EGL_BAD_MATCH
        at com.simonlee.scanner.core.TextureReader.initEGL(TextureReader.java:242)
        at com.simonlee.scanner.core.TextureReader.run(TextureReader.java:191)

**Comment by Simon-Leeeeeeeee** [comment]
好的，感谢反馈，会尽快修复这个bug
